// Generated by astgen // -*- mode: C++; c-file-style: "cc-mode" -*-
class DfgAcosD final : public DfgVertexUnary {
public:
    DfgAcosD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAcosD;
};
class DfgAcoshD final : public DfgVertexUnary {
public:
    DfgAcoshD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAcoshD;
};
class DfgAdd final : public DfgVertexBinary {
public:
    DfgAdd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAdd;
};
class DfgAddD final : public DfgVertexBinary {
public:
    DfgAddD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAddD;
};
class DfgAnd final : public DfgVertexBinary {
public:
    DfgAnd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAnd;
};
class DfgArraySel final : public DfgVertexBinary {
public:
    DfgArraySel(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgArraySel;
};
class DfgAsinD final : public DfgVertexUnary {
public:
    DfgAsinD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAsinD;
};
class DfgAsinhD final : public DfgVertexUnary {
public:
    DfgAsinhD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAsinhD;
};
class DfgAssocSel final : public DfgVertexBinary {
public:
    DfgAssocSel(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAssocSel;
};
class DfgAtan2D final : public DfgVertexBinary {
public:
    DfgAtan2D(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAtan2D;
};
class DfgAtanD final : public DfgVertexUnary {
public:
    DfgAtanD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAtanD;
};
class DfgAtanhD final : public DfgVertexUnary {
public:
    DfgAtanhD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAtanhD;
};
class DfgAtoN final : public DfgVertexUnary {
public:
    DfgAtoN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgAtoN;
};
class DfgBitsToRealD final : public DfgVertexUnary {
public:
    DfgBitsToRealD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgBitsToRealD;
};
class DfgBufIf1 final : public DfgVertexBinary {
public:
    DfgBufIf1(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgBufIf1;
};
class DfgCAwait final : public DfgVertexUnary {
public:
    DfgCAwait(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCAwait;
};
class DfgCCast final : public DfgVertexUnary {
public:
    DfgCCast(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCCast;
};
class DfgCLog2 final : public DfgVertexUnary {
public:
    DfgCLog2(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCLog2;
};
class DfgCastDynamic final : public DfgVertexBinary {
public:
    DfgCastDynamic(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCastDynamic;
};
class DfgCastWrap final : public DfgVertexUnary {
public:
    DfgCastWrap(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCastWrap;
};
class DfgCeilD final : public DfgVertexUnary {
public:
    DfgCeilD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCeilD;
};
class DfgCompareNN final : public DfgVertexBinary {
public:
    DfgCompareNN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCompareNN;
};
class DfgConcat final : public DfgVertexBinary {
public:
    DfgConcat(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgConcat;
};
class DfgConcatN final : public DfgVertexBinary {
public:
    DfgConcatN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgConcatN;
};
class DfgCond final : public DfgVertexTernary {
public:
    DfgCond(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCond;
};
class DfgCondBound final : public DfgVertexTernary {
public:
    DfgCondBound(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCondBound;
};
class DfgCosD final : public DfgVertexUnary {
public:
    DfgCosD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCosD;
};
class DfgCoshD final : public DfgVertexUnary {
public:
    DfgCoshD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCoshD;
};
class DfgCountOnes final : public DfgVertexUnary {
public:
    DfgCountOnes(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCountOnes;
};
class DfgCvtPackString final : public DfgVertexUnary {
public:
    DfgCvtPackString(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgCvtPackString;
};
class DfgDistChiSquare final : public DfgVertexBinary {
public:
    DfgDistChiSquare(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistChiSquare;
};
class DfgDistErlang final : public DfgVertexTernary {
public:
    DfgDistErlang(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistErlang;
};
class DfgDistExponential final : public DfgVertexBinary {
public:
    DfgDistExponential(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistExponential;
};
class DfgDistNormal final : public DfgVertexTernary {
public:
    DfgDistNormal(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistNormal;
};
class DfgDistPoisson final : public DfgVertexBinary {
public:
    DfgDistPoisson(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistPoisson;
};
class DfgDistT final : public DfgVertexBinary {
public:
    DfgDistT(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistT;
};
class DfgDistUniform final : public DfgVertexTernary {
public:
    DfgDistUniform(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDistUniform;
};
class DfgDiv final : public DfgVertexBinary {
public:
    DfgDiv(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDiv;
};
class DfgDivD final : public DfgVertexBinary {
public:
    DfgDivD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDivD;
};
class DfgDivS final : public DfgVertexBinary {
public:
    DfgDivS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgDivS;
};
class DfgEq final : public DfgVertexBinary {
public:
    DfgEq(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEq;
};
class DfgEqCase final : public DfgVertexBinary {
public:
    DfgEqCase(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEqCase;
};
class DfgEqD final : public DfgVertexBinary {
public:
    DfgEqD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEqD;
};
class DfgEqN final : public DfgVertexBinary {
public:
    DfgEqN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEqN;
};
class DfgEqT final : public DfgVertexBinary {
public:
    DfgEqT(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEqT;
};
class DfgEqWild final : public DfgVertexBinary {
public:
    DfgEqWild(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgEqWild;
};
class DfgExpD final : public DfgVertexUnary {
public:
    DfgExpD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgExpD;
};
class DfgExtend final : public DfgVertexUnary {
public:
    DfgExtend(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgExtend;
};
class DfgExtendS final : public DfgVertexUnary {
public:
    DfgExtendS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgExtendS;
};
class DfgFEof final : public DfgVertexUnary {
public:
    DfgFEof(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgFEof;
};
class DfgFGetC final : public DfgVertexUnary {
public:
    DfgFGetC(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgFGetC;
};
class DfgFGetS final : public DfgVertexBinary {
public:
    DfgFGetS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgFGetS;
};
class DfgFUngetC final : public DfgVertexBinary {
public:
    DfgFUngetC(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgFUngetC;
};
class DfgFloorD final : public DfgVertexUnary {
public:
    DfgFloorD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgFloorD;
};
class DfgGetcN final : public DfgVertexBinary {
public:
    DfgGetcN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGetcN;
};
class DfgGetcRefN final : public DfgVertexBinary {
public:
    DfgGetcRefN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGetcRefN;
};
class DfgGt final : public DfgVertexBinary {
public:
    DfgGt(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGt;
};
class DfgGtD final : public DfgVertexBinary {
public:
    DfgGtD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGtD;
};
class DfgGtN final : public DfgVertexBinary {
public:
    DfgGtN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGtN;
};
class DfgGtS final : public DfgVertexBinary {
public:
    DfgGtS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGtS;
};
class DfgGte final : public DfgVertexBinary {
public:
    DfgGte(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGte;
};
class DfgGteD final : public DfgVertexBinary {
public:
    DfgGteD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGteD;
};
class DfgGteN final : public DfgVertexBinary {
public:
    DfgGteN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGteN;
};
class DfgGteS final : public DfgVertexBinary {
public:
    DfgGteS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgGteS;
};
class DfgHypotD final : public DfgVertexBinary {
public:
    DfgHypotD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgHypotD;
};
class DfgISToRD final : public DfgVertexUnary {
public:
    DfgISToRD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgISToRD;
};
class DfgIToRD final : public DfgVertexUnary {
public:
    DfgIToRD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgIToRD;
};
class DfgIsUnbounded final : public DfgVertexUnary {
public:
    DfgIsUnbounded(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgIsUnbounded;
};
class DfgIsUnknown final : public DfgVertexUnary {
public:
    DfgIsUnknown(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgIsUnknown;
};
class DfgLenN final : public DfgVertexUnary {
public:
    DfgLenN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLenN;
};
class DfgLog10D final : public DfgVertexUnary {
public:
    DfgLog10D(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLog10D;
};
class DfgLogAnd final : public DfgVertexBinary {
public:
    DfgLogAnd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogAnd;
};
class DfgLogD final : public DfgVertexUnary {
public:
    DfgLogD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogD;
};
class DfgLogEq final : public DfgVertexBinary {
public:
    DfgLogEq(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogEq;
};
class DfgLogIf final : public DfgVertexBinary {
public:
    DfgLogIf(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogIf;
};
class DfgLogNot final : public DfgVertexUnary {
public:
    DfgLogNot(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogNot;
};
class DfgLogOr final : public DfgVertexBinary {
public:
    DfgLogOr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLogOr;
};
class DfgLt final : public DfgVertexBinary {
public:
    DfgLt(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLt;
};
class DfgLtD final : public DfgVertexBinary {
public:
    DfgLtD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLtD;
};
class DfgLtN final : public DfgVertexBinary {
public:
    DfgLtN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLtN;
};
class DfgLtS final : public DfgVertexBinary {
public:
    DfgLtS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLtS;
};
class DfgLte final : public DfgVertexBinary {
public:
    DfgLte(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLte;
};
class DfgLteD final : public DfgVertexBinary {
public:
    DfgLteD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLteD;
};
class DfgLteN final : public DfgVertexBinary {
public:
    DfgLteN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLteN;
};
class DfgLteS final : public DfgVertexBinary {
public:
    DfgLteS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgLteS;
};
class DfgModDiv final : public DfgVertexBinary {
public:
    DfgModDiv(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgModDiv;
};
class DfgModDivS final : public DfgVertexBinary {
public:
    DfgModDivS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgModDivS;
};
class DfgMul final : public DfgVertexBinary {
public:
    DfgMul(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgMul;
};
class DfgMulD final : public DfgVertexBinary {
public:
    DfgMulD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgMulD;
};
class DfgMulS final : public DfgVertexBinary {
public:
    DfgMulS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgMulS;
};
class DfgNToI final : public DfgVertexUnary {
public:
    DfgNToI(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNToI;
};
class DfgNegate final : public DfgVertexUnary {
public:
    DfgNegate(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNegate;
};
class DfgNegateD final : public DfgVertexUnary {
public:
    DfgNegateD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNegateD;
};
class DfgNeq final : public DfgVertexBinary {
public:
    DfgNeq(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeq;
};
class DfgNeqCase final : public DfgVertexBinary {
public:
    DfgNeqCase(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeqCase;
};
class DfgNeqD final : public DfgVertexBinary {
public:
    DfgNeqD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeqD;
};
class DfgNeqN final : public DfgVertexBinary {
public:
    DfgNeqN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeqN;
};
class DfgNeqT final : public DfgVertexBinary {
public:
    DfgNeqT(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeqT;
};
class DfgNeqWild final : public DfgVertexBinary {
public:
    DfgNeqWild(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNeqWild;
};
class DfgNot final : public DfgVertexUnary {
public:
    DfgNot(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNot;
};
class DfgNullCheck final : public DfgVertexUnary {
public:
    DfgNullCheck(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgNullCheck;
};
class DfgOneHot final : public DfgVertexUnary {
public:
    DfgOneHot(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgOneHot;
};
class DfgOneHot0 final : public DfgVertexUnary {
public:
    DfgOneHot0(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgOneHot0;
};
class DfgOr final : public DfgVertexBinary {
public:
    DfgOr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgOr;
};
class DfgPostAdd final : public DfgVertexTernary {
public:
    DfgPostAdd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPostAdd;
};
class DfgPostSub final : public DfgVertexTernary {
public:
    DfgPostSub(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPostSub;
};
class DfgPow final : public DfgVertexBinary {
public:
    DfgPow(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPow;
};
class DfgPowD final : public DfgVertexBinary {
public:
    DfgPowD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPowD;
};
class DfgPowSS final : public DfgVertexBinary {
public:
    DfgPowSS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPowSS;
};
class DfgPowSU final : public DfgVertexBinary {
public:
    DfgPowSU(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPowSU;
};
class DfgPowUS final : public DfgVertexBinary {
public:
    DfgPowUS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPowUS;
};
class DfgPreAdd final : public DfgVertexTernary {
public:
    DfgPreAdd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPreAdd;
};
class DfgPreSub final : public DfgVertexTernary {
public:
    DfgPreSub(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPreSub;
};
class DfgPutcN final : public DfgVertexTernary {
public:
    DfgPutcN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgPutcN;
};
class DfgRToIRoundS final : public DfgVertexUnary {
public:
    DfgRToIRoundS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRToIRoundS;
};
class DfgRToIS final : public DfgVertexUnary {
public:
    DfgRToIS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRToIS;
};
class DfgRealToBits final : public DfgVertexUnary {
public:
    DfgRealToBits(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRealToBits;
};
class DfgRedAnd final : public DfgVertexUnary {
public:
    DfgRedAnd(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRedAnd;
};
class DfgRedOr final : public DfgVertexUnary {
public:
    DfgRedOr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRedOr;
};
class DfgRedXor final : public DfgVertexUnary {
public:
    DfgRedXor(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgRedXor;
};
class DfgReplicate final : public DfgVertexBinary {
public:
    DfgReplicate(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgReplicate;
};
class DfgReplicateN final : public DfgVertexBinary {
public:
    DfgReplicateN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgReplicateN;
};
class DfgResizeLValue final : public DfgVertexUnary {
public:
    DfgResizeLValue(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgResizeLValue;
};
class DfgShiftL final : public DfgVertexBinary {
public:
    DfgShiftL(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftL;
};
class DfgShiftLOvr final : public DfgVertexBinary {
public:
    DfgShiftLOvr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftLOvr;
};
class DfgShiftR final : public DfgVertexBinary {
public:
    DfgShiftR(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftR;
};
class DfgShiftROvr final : public DfgVertexBinary {
public:
    DfgShiftROvr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftROvr;
};
class DfgShiftRS final : public DfgVertexBinary {
public:
    DfgShiftRS(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftRS;
};
class DfgShiftRSOvr final : public DfgVertexBinary {
public:
    DfgShiftRSOvr(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgShiftRSOvr;
};
class DfgSigned final : public DfgVertexUnary {
public:
    DfgSigned(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSigned;
};
class DfgSinD final : public DfgVertexUnary {
public:
    DfgSinD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSinD;
};
class DfgSinhD final : public DfgVertexUnary {
public:
    DfgSinhD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSinhD;
};
class DfgSliceSel final : public DfgVertexTernary {
public:
    DfgSliceSel(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSliceSel;
};
class DfgSqrtD final : public DfgVertexUnary {
public:
    DfgSqrtD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSqrtD;
};
class DfgStreamL final : public DfgVertexBinary {
public:
    DfgStreamL(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgStreamL;
};
class DfgStreamR final : public DfgVertexBinary {
public:
    DfgStreamR(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgStreamR;
};
class DfgSub final : public DfgVertexBinary {
public:
    DfgSub(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSub;
};
class DfgSubD final : public DfgVertexBinary {
public:
    DfgSubD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSubD;
};
class DfgSubstrN final : public DfgVertexTernary {
public:
    DfgSubstrN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexTernary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgSubstrN;
};
class DfgTanD final : public DfgVertexUnary {
public:
    DfgTanD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgTanD;
};
class DfgTanhD final : public DfgVertexUnary {
public:
    DfgTanhD(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgTanhD;
};
class DfgTimeImport final : public DfgVertexUnary {
public:
    DfgTimeImport(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgTimeImport;
};
class DfgToLowerN final : public DfgVertexUnary {
public:
    DfgToLowerN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgToLowerN;
};
class DfgToUpperN final : public DfgVertexUnary {
public:
    DfgToUpperN(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgToUpperN;
};
class DfgURandomRange final : public DfgVertexBinary {
public:
    DfgURandomRange(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgURandomRange;
};
class DfgUnsigned final : public DfgVertexUnary {
public:
    DfgUnsigned(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexUnary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgUnsigned;
};
class DfgWildcardSel final : public DfgVertexBinary {
public:
    DfgWildcardSel(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgWildcardSel;
};
class DfgWordSel final : public DfgVertexBinary {
public:
    DfgWordSel(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgWordSel;
};
class DfgXor final : public DfgVertexBinary {
public:
    DfgXor(DfgGraph& dfg, FileLine* flp, AstNodeDType* dtypep)
        : DfgVertexBinary{dfg, dfgType(), flp, dtypep} {}
    ASTGEN_MEMBERS_DfgXor;
};

